import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layouts/NavBar";
import SmoothScrollProvider from "@/components/layouts/SmoothScrollProvider";
import Footer from "@/components/layouts/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Green Wave Packaging",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} bg-[#f5f8f6] ${geistMono.variable} antialiased`}
      >
        <SmoothScrollProvider>
          <nav>
            <NavBar />
          </nav>

          {children}
          <footer>
            <Footer />
          </footer>
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
